FROM golang:1.22-alpine AS builder

WORKDIR /app
COPY . .

RUN go mod init monitor-agent && \
    go mod tidy && \
    go build -o agent .

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/agent .

CMD ["./agent"]
